databases:
  - name: rails-camp-app-db
    databaseName: camp
    user: yamato
    region: singapore

services:
  - type: web
    name: rails-camp-app
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-camp-app-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
